version: "3.9"
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - backend_data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:80"
    restart: unless-stopped

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  backend_data:
  caddy_data:
  caddy_config:
